name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Sideproject posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://sideproject.buzzing.cc/lite/feed.xml"
          max_post_count: 20
          comment_tag_name: "sideproject"
          date_format: "UTC: dd"
          template: "$newline- $date [$title]($url)"
          filter_dates: "daysAgo/1/"
      - name: Pull in 无忧分享 posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://51.ruyo.net/feed"
          max_post_count: 3
          comment_tag_name: "ruyo"
          date_format: "UTC: dd"
          template: "$newline- $date [$title]($url)"
          filter_dates: "daysAgo/1/"
      - name: Pull in advertcn posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.advertcn.com/forum.php?mod=guide&view=hot&rss=1"
          max_post_count: 10
          comment_tag_name: "advertcn"
          date_format: "UTC: dd"
          template: "$newline- $date [$title]($url)"
          filter_dates: "daysAgo/1/"
      - name: Pull in afflift posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://afflift.com/f/forums/-/index.rss"
          max_post_count: 12
          comment_tag_name: "afflift"
          date_format: "UTC: dd"
          template: "$newline- $date [$title]($url)"
          filter_dates: "daysAgo/1/"
      - name: Pull in sspai posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://sspai.com/feed"
          max_post_count: 5
          comment_tag_name: "sspai"
          date_format: "UTC: dd"
          template: "$newline- $date [$title]($url)"
          filter_dates: "daysAgo/1/"
      
  
