name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in bbc posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "http://www.bbc.co.uk/zhongwen/simp/index.xml"
          max_post_count: 5
          comment_tag_name: "bbc"
          date_format: "UTC: dd"
          template: "$newline- $date [$title]($url)"
          filter_dates: "daysAgo/1/"
      - name: Pull in voa posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.voachinese.com/api/zm_yqebbyi"
          max_post_count: 10
          comment_tag_name: "voa"
          date_format: "UTC: dd"
          template: "$newline- $date [$title]($url)"
          filter_dates: "daysAgo/1/"
      - name: Pull in dw posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rss.dw.com/atom/rss-chi-all"
          max_post_count: 10
          comment_tag_name: "dw"
          date_format: "UTC: dd"
          template: "$newline- $date [$title]($url)"
          filter_dates: "daysAgo/1/"
      - name: Pull in nytimes posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://cn.nytimes.com/rss/"
          max_post_count: 8
          comment_tag_name: "nytimes"
          date_format: "UTC: dd"
          template: "$newline- $date [$title]($url)"
          filter_dates: "daysAgo/1/"
      - name: Pull in FR posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://feedx.net/rss/rfi.xml"
          max_post_count: 10
          comment_tag_name: "FR"
          date_format: "UTC: dd"
          template: "$newline- $date [$title]($url)"
          filter_dates: "daysAgo/1/"